routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   echo "HELLO. YOU ARE AT ADMIN SITE.";
});

routes/web.php
<?php

use App\Http\Controllers\AllUserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BahagianController;
use \Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::middleware('auth')
    ->group(function() {
    Route::get('users/update_password', [UserController::class, 'updatePasswordForm'])
        ->name('users.update_password');
    Route::put('users/update_password', [UserController::class, 'updatePasswordSubmit'])
        ->name('users.update_password_submit');

    Route::get('/publicusers/{id}', [UserController::class, 'exportToPdf']);

    Route::resource('/publicusers', UserController::class)->only(['index','show']);

    Route::prefix('admin')
        ->group(function() {
        Route::resource('/users', UserController::class);
        Route::resource('/bahagian', BahagianController::class);
    });
});

Route::get('/get-all-user', AllUserController::class);

//http://booking.test/test
Route::get('/test', function() {
    echo "HELLO, WORLD";
});

//http://booking.test/test/1/apa2
//http://booking.test/test/1
Route::get('/test/{a}/{name?}', function ($id, $name = null)
{
   echo "Hello, " . $id . $name ;
});

//http://booking.test/clash/kereta
Route::get('/clash/kereta', function() {
    echo "Masuk Situ Kereta" ;
});

//http://booking.test/clash/1
Route::get('/clash/{id}', function($id) {
    echo "Masuk Sini " . $id;
});

Route::get('/rawsql', function() {
    $users = DB::select("SELECT * FROM users WHERE id=? OR id=?", [1,400]);
    return $users;
});

app/Models/Bahagian.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bahagian extends Model
{
    use HasFactory;

    protected $table = 'bahagian';

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'nama',
    ];

    public function ketua()
    {
        return $this->belongsTo(User::class, 'ketua_id');
    }

}

app/Http/Controllers/BahagianController.php
<?php

namespace App\Http\Controllers;

use App\Models\Bahagian;
use Illuminate\Http\Request;

class BahagianController extends Controller
{
    /**
     * Senaraikan semua pengguna
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // dapatkan data bahagians dari table bahagian
        $bahagians = Bahagian::get();

        // paparkan data tersebut
        return view('bahagian.index', compact('bahagians'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // paparkan form
        return view('bahagian.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate submitted data
        $request->validate([
            'nama' => 'required|max:255|min:2',
        ]);

        // dapatkan data & prepare rekod baru
        // mass assignment demo
        Bahagian::create(request()->all());

        // notification save is success

        // redirect page ke listing (index)
        return redirect(route('bahagian.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // dapatkan rekod mengikut ID yang diberi
        $bahagian = Bahagian::findOrFail($id);

        // paparkan rekod
        return view('bahagian.show', compact('bahagian'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Bahagian  $bahagian
     * @return \Illuminate\Http\Response
     */
    public function edit(Bahagian $bahagian)
    {
        $senarai_jabatan = [
            'A1', 'A2', 'BPM', 'C1'
        ];
        // dapatkan senarai bahagians untuk dijadikan supervisor
        $bahagians = Bahagian::orderBy('nama')
            //->where('id', '!=', $bahagian->id)
            ->get();

        // paparkan form
        return view('bahagian.edit', [
            'bahagian' => $bahagian,
            'senarai_supervisor' => $bahagians,
            'senarai_jabatan' => $senarai_jabatan
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dapatkan data yang nak dikemaskini
        $bahagian = Bahagian::where('id', $id)->firstOrFail();

        // validate data yang disubmit
        $request->validate([
            'nama' => 'required|max:255|min:2',
        ]);

        // kemaskini rekod menggunakan data yg disubmit
        $bahagian->kod = request()->kod;
        $bahagian->nama = request()->nama;

        // save ke database
        $bahagian->save();

        // notification success

        // redirect ke page bahagians
        return redirect(route('bahagian.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // dapatkan rekod bahagian yg hendak dibuang
        $bahagian = Bahagian::where('id', $id)->firstOrFail();

        // buang rekod
        $bahagian->delete();

        // notifikasi berjaya

        // redirect ke listing
        return redirect(route('bahagian.index'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/bahagian/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Bahagian') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                <form method="POST" action="{{ route('bahagian.store') }}">
                    @csrf

                    <!-- Kod -->
                    <div class="mb-3">
                        <label for="kod" class="form-label">Kod</label>
                        <input type="text" class="form-control" id="kod"
                               name="kod" :value="old('kod')" required autofocus
                        >
                        @error('kod')
                        <div class="text-red">{{ $message }}</div>
                        @enderror
                    </div>

                    <!-- Name -->
                    <div class="mb-3">
                        <label for="nama" class="form-label">Nama</label>
                        <input type="text" class="form-control" id="nama"
                            name="nama" :value="old('nama')" required autofocus
                        >
                        @error('nama')
                            <div class="text-red">{{ $message }}</div>
                        @enderror
                    </div>

                    <div class="pt-4">
                        <button class="btn btn-primary">
                            {{ __('Submit') }}
                        </button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/bahagian/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Users') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                <form method="POST" action="{{ route('bahagians.update', $bahagian) }}">
                    @csrf
                    @method('PUT')

                    <!-- Kod -->
                        <div class="mb-3">
                            <label for="kod" class="form-label">Kod</label>
                            <input type="text" class="form-control" id="kod"
                                   name="kod" :value="old('kod')" required autofocus
                            >
                            @error('kod')
                            <div class="text-red">{{ $message }}</div>
                            @enderror
                        </div>

                        <!-- Name -->
                        <div class="mb-3">
                            <label for="nama" class="form-label">Nama</label>
                            <input type="text" class="form-control" id="nama"
                                   name="nama" :value="old('nama')" required autofocus
                            >
                            @error('nama')
                            <div class="text-red">{{ $message }}</div>
                            @enderror
                        </div>

                    <div class="pt-4">
                        <button class="btn btn-primary">
                            {{ __('Submit') }}
                        </button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/bahagian/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <span class="header-brand mb-0 h3">{{ __('Bahagian') }}</span>
    </x-slot>

    <div>
        <div class="container p-2">
            <a href="{{ route('bahagian.create')}}"
                class="btn btn-success"
            > Add New Bahagian </a>
        </div>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th></th>
            </tr>
            @foreach($bahagians as $bahagian)
                @if ($loop->first)
                    <tr>
                        <td colspan='4'> FIRST ROW </td>
                    </tr>
                @endif
                <tr>
                    <td>{{ $bahagian->id }}</td>
                    <td>{{ $bahagian->kod }}</td>
                    <td>{{ $bahagian->nama }}</td>
                    <td>
                        <a href="{{ route('bahagian.show', $bahagian)}}"
                            class="btn btn-success"
                        > View </a>
                        <a href="{{ route('bahagian.edit', $bahagian)}}"
                            class="btn btn-success"
                        > Edit </a>
                        <form action="{{ route('bahagian.destroy', $bahagian)}}"
                            method="POST" style="float:right">
                            @csrf
                            @method('delete')
                         <button class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                @if ($loop->last)
                    <tr>
                        <td colspan='4'> LAST ROW </td>
                    </tr>
                @endif
            @endforeach
        </table>
    </div>
</x-app-layout>

resources/views/bahagian/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Maklumat User') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">    
                <table class="table">
                    <tr>
                        <td>Name</td>
                        <td>{{ $user->name }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>{{ $user->email }}</td>
                    </tr>                   
                </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/bahagian/update_password.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Users') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                <form method="POST" action="{{ route('users.update_password_submit') }}">
                    @csrf
                    @method('PUT')

                    <!-- Password -->
                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password"
                               name="password" :value="old('password')" required
                        >
                        @error('password')
                        <div class="text-red">{{ $message }}</div>
                        @enderror
                    </div>

                    <!-- Confirm Password -->
                    <div class="mb-3">
                        <label for="password_confirmation" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password_confirmation"
                               name="password_confirmation" :value="old('password_confirmation')" required
                        >
                        @error('password_confirmation')
                        <div class="text-red">{{ $message }}</div>
                        @enderror
                    </div>

                    <div class="pt-4">
                        <button class="btn btn-primary">
                            {{ __('Submit') }}
                        </button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>