routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   echo "HELLO. YOU ARE AT ADMIN SITE.";
});

routes/web.php
<?php

use App\Http\Controllers\AllUserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BahagianController;
use \Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::middleware('auth')
    ->group(function() {
    Route::get('users/update_password', [UserController::class, 'updatePasswordForm'])
        ->name('users.update_password');
    Route::put('users/update_password', [UserController::class, 'updatePasswordSubmit'])
        ->name('users.update_password_submit');

    Route::get('/publicusers/{id}', [UserController::class, 'exportToPdf']);

    Route::resource('/publicusers', UserController::class)->only(['index','show']);

    Route::prefix('admin')
        ->group(function() {
        Route::resource('/users', UserController::class);
        Route::resource('/bahagian', BahagianController::class);
    });
});

Route::get('/get-all-user', AllUserController::class);

//http://booking.test/test
Route::get('/test', function() {
    echo "HELLO, WORLD";
});

//http://booking.test/test/1/apa2
//http://booking.test/test/1
Route::get('/test/{a}/{name?}', function ($id, $name = null)
{
   echo "Hello, " . $id . $name ;
});

//http://booking.test/clash/kereta
Route::get('/clash/kereta', function() {
    echo "Masuk Situ Kereta" ;
});

//http://booking.test/clash/1
Route::get('/clash/{id}', function($id) {
    echo "Masuk Sini " . $id;
});

Route::get('/rawsql', function() {
    $users = DB::select("SELECT * FROM users WHERE id=? OR id=?", [1,400]);
    return $users;
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Seorang penjawat boleh menjadi ketua dia banyak bahagian
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function bahagians()
    {
        return $this->hasMany(Bahagian::class, 'ketua_id');
    }

    /**
     * seorang penjawat bekerja dibawah bahagian
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function bahagian()
    {
        return $this->belongsTo(Bahagian::class, 'bahagian_id');
    }

    public function getNameEmailAttribute()
    {
        return $this->name . " <" . $this->email . ">";
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Bahagian;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    /**
     * Senaraikan semua pengguna
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // dapatkan value search
        $search = request()->search;
        $search2 = request()->search2;

        // dapatkan data users dari table user
        // tarik sekali relationship bahagians dengan eager loading
//        $users_query = User::with('bahagians');
//
//        if (!empty($search)) {
//            $users_query->where('name', $search)
//                ->OrWhere('email', $search)
//                ;
//        }

        $users = User::with(['bahagians' => function($query) use ($search2) {
                            $query->when($search2, function($query) use ($search2) {
                                $query->where('kod', 'LIKE', "%" . $search2 . "%")
                                    ->OrWhere('nama', 'LIKE', "%" . $search2 . "%")
                                ;
                            });
                            }, 'bahagian']
                    )
                    ->when($search, function($query) use ($search) {
                            $query->where('name', 'LIKE', "%" . $search . "%")
                                    ->OrWhere('email', 'LIKE', "%" . $search . "%")
                                    ->orWhereHas('bahagian', function($query) use ($search) {
                                        $query->where('kod', 'LIKE', "%" . $search . "%")
                                            ->OrWhere('nama', 'LIKE', "%" . $search . "%")
                                        ;
                                    })
                                    ->orWhereHas('bahagians', function($query) use ($search) {
                                        $query->where('kod', 'LIKE', "%" . $search . "%")
                                            ->OrWhere('nama', 'LIKE', "%" . $search . "%")
                                        ;
                                    })
                            ;
                    })
//                    ->whereDay('created_at', '28')
//                    ->whereMonth('created_at', '9')
//                    ->whereYear('created_at', '2021')
//                    ->whereDate('created_at', '2021-09-28')
                    ->paginate(20);

        // SELECT *
        // FROM users
        // WHERE name LIKE '%$search5'
        // OR email LIKE '%$search%'
        // OR bahagian_id IN (
        //         SELECT id FROM bahagian WHERE  where kod LIKE '%$search5'
        //         OR nama LIKE '%$search%'
        //  )
        // paparkan data tersebut
        return view('user.index', compact('users','search', 'search2'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // paparkan form
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate submitted data
        $request->validate([
            'name' => 'required|max:255|min:2',
            'email' => 'required|unique:users',
            'password' => 'required|confirmed',
        ]);

        // dapatkan data & prepare rekod baru
        $user = new User();

        $user->name = request()->name;
        $user->email = request()->email;
        $user->password = Hash::make(request()->password);

        // save rekod baru
        $user->save();

        // notification save is success

        // redirect page ke listing (index)
        return redirect(route('users.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // dapatkan rekod mengikut ID yang diberi
        $user = User::with('bahagians')->findOrFail($id);

        // paparkan rekod
        return view('user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $senarai_bahagian = Bahagian::orderBy('nama')->get();
        // dapatkan senarai users untuk dijadikan supervisor
        $users = User::orderBy('name')
                    //->where('id', '!=', $user->id)
                    ->get();

         // paparkan form
        return view('user.edit', [
                'user' => $user,
                'senarai_supervisor' => $users,
                'senarai_bahagian' => $senarai_bahagian
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dapatkan data yang nak dikemaskini
        $user = User::where('id', $id)->firstOrFail();

        // validate data yang disubmit
        $request->validate([
            'name' => ['required', 'max:255', 'min:2'],
            'email' => [
                'required',
                Rule::unique('users')->ignore($user->id),
            ]
        ]);

        // kemaskini rekod menggunakan data yg disubmit
        $user->name = request()->name;
        $user->email = request()->email;
        $user->bahagian_id  = request()->bahagian_id;

        // save ke database
        $user->save();

        // notification success

        // redirect ke page users
        return redirect(route('users.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // dapatkan rekod user yg hendak dibuang
        $user = User::where('id', $id)->firstOrFail();

        // buang rekod
        $user->delete();

        // notifikasi berjaya

        // redirect ke listing
        return redirect(route('users.index'));
    }

    /**
     * display form untuk update password
     */
    public function updatePasswordForm()
    {
        return view('user.update_password');
    }

    public function updatePasswordSubmit()
    {
        // validate
        request()->validate([
            'password' => 'required|confirmed',
        ]);
        // get user untuk dikemaskini (current user yg logged in)
        $user = auth()->user();
        //kemaskini rekod
        $user->password = Hash::make(request()->password);
        $user->save();
        //redirect ke index
        return redirect(route('users.index'));
    }

    public function exportToPdf($id) {
        $user = User::with('bahagians')->findOrFail($id);

        $pdf = \PDF::loadView('user.pdfexport', compact('user'));
        return $pdf->stream();
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/user/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Users') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                <form method="POST" action="{{ route('users.store') }}">
                    @csrf

                    <!-- Name -->
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name"
                            name="name" :value="old('name')" required autofocus
                        >
                        @error('name')
                            <div class="text-red">{{ $message }}</div>
                        @enderror
                    </div>

                    <!-- Email Address -->
                    <div class="mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email"
                               name="email" :value="old('email')" required
                        >
                        @error('email')
                        <div class="text-red">{{ $message }}</div>
                        @enderror
                    </div>

                    <!-- Password -->
                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password"
                               name="password" :value="old('password')" required
                        >
                        @error('password')
                        <div class="text-red">{{ $message }}</div>
                        @enderror
                    </div>

                    <!-- Confirm Password -->
                    <div class="mb-3">
                        <label for="password_confirmation" class="form-label">Password</label>
                        <input type="password_confirmation" class="form-control" id="password_confirmation"
                               name="password_confirmation" :value="old('password_confirmation')" required
                        >
                        @error('password_confirmation')
                        <div class="text-red">{{ $message }}</div>
                        @enderror
                    </div>

                    <div class="pt-4">
                        <button class="btn btn-primary">
                            {{ __('Submit') }}
                        </button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/user/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Users') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                <form method="POST" action="{{ route('users.update', $user) }}">
                    @csrf
                    @method('PUT')

                    <!-- Name -->
                        <div class="mb-3">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" class="form-control" id="name"
                                   name="name" value="{{ old('name', $user->name) }}" required autofocus
                            >
                            @error('name')
                            <div class="text-red">{{ $message }}</div>
                            @enderror
                        </div>

                        <!-- Email Address -->
                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" id="email"
                                   name="email" value="{{ old('email', $user->email) }}" required
                            >
                            @error('email')
                            <div class="text-red">{{ $message }}</div>
                            @enderror
                        </div>

                    <div class="mt-4">
                        <label for="jabatan_id"> Bahagian </label>
                        <select
                            id="bahagian_id" class="form-control"
                            name="bahagian_id"
                        />
                            <option value="">Sila Pilih</option>
                            @foreach($senarai_bahagian as $index => $bahagian)
                                <option
                                    value="{{ $bahagian->id }}"
                                    @if($bahagian->id == old('bahagian_id', $user->bahagian_id)) selected @endif
                                >{{ $bahagian->nama }}</option>
                            @endforeach

                        </select>
                        @error('bahagian_id')
                            <div class="text-red">{{ $message }}</div>
                        @enderror
                    </div>

                    <div class="mt-4">
                        <label for="supervisor_id"> Supervisor </label>
                        <select
                            id="supervisor_id" class="form-control"
                            name="supervisor_id"
                        />
                            <option value="">Sila Pilih</option>
                            @foreach($senarai_supervisor as $index => $supervisor)
                                @if($supervisor->id != $user->id)
                                    <option value="{{ $supervisor->id }}">{{ $supervisor->name }}</option>
                                @else
                                    <option value="{{ $supervisor->id }}">Current User</option>
                                @endif
                            @endforeach
                        </select>
                        @error('supervisor_id')
                            <div class="text-red">{{ $message }}</div>
                        @enderror
                    </div>

                    <div class="pt-4">
                        <button class="btn btn-primary">
                            {{ __('Submit') }}
                        </button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/user/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <span class="header-brand mb-0 h3">{{ __('Users') }}</span>
    </x-slot>

    <div>
        <div class="container p-2">
            <a href="{{ route('users.update_password')}}"
                class="btn btn-primary"
            > Update My Password </a>
            <a href="{{ route('users.create')}}"
                class="btn btn-success"
            > Add New User </a>
        </div>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Mengetuai</th>
                <th>Bahagian</th>
                <th>Register date</th>
                <th></th>
            </tr>
            <tr>
                <td colspan="7">
                    <form action="">
                        <div class="row">
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="search"
                                       name="search" value="{{ $search ?? '' }}"
                                       placeholder="Search"
                                >
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="search2"
                                       name="search2" value="{{ $search2 ?? '' }}"
                                       placeholder="Search2"
                                >
                            </div>
                        </div>
                        <div class="row">
                            <button class="btn btn-primary m-2">Search</button>
                        </div>
                    </form>
                </td>
            </tr>
            @foreach($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->name_email }}</td>
                    <td>
                        @foreach($user->bahagians as $bahagian)
                            {{ $bahagian->nama }},
                        @endforeach
                    </td>
                    <td>
                        {{ $user->bahagian->nama ?? 'N/A' }}
                    </td>
                    <td>{{  $user->created_at->format('M Y') }}</td>
                    <td>
                        <a href="{{ route('users.show', $user)}}"
                            class="btn btn-success"
                        > View </a>
                        <a href="{{ route('users.edit', $user)}}"
                            class="btn btn-success"
                        > Edit </a>
                        <form action="{{ route('users.destroy', $user)}}"
                            method="POST" style="float:right">
                            @csrf
                            @method('delete')
                         <button class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
        {{ $users->appends(request()->all())->links() }}
    </div>
</x-app-layout>

resources/views/user/pdfexport.blade.php
<html>
<head></head>
<body>
    <table>
        <tr><td>Name</td><td>{{ $user->name }}</td></tr>
        <tr><td>Email</td><td>{{ $user->email }}</td></tr>
        <tr>
            <td>Bahagian</td>
            <td>
                <table class="table table-striped">
                    @foreach($user->bahagians as $bahagian)
                        <tr>
                            <td width="10px">{{ $loop->iteration }}</td>
                            <td>{{ $bahagian->nama }}</td>
                        </tr>
                    @endforeach
                </table>
            </td>
        </tr>
    </table>
</body>
</html>

resources/views/user/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Maklumat User') }}
        </h2>
    </x-slot>

    <div class="container">
        <table class="table table-sm table-hover">
            <tr>
                <td>Name</td>
                <td>{{ $user->name }}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ $user->email }}</td>
            </tr>
            <tr>
                <td>Bahagian</td>
                <td>
                    <table class="table table-striped">
                        @foreach($user->bahagians as $bahagian)
                            <tr>
                                <td width="10px">{{ $loop->iteration }}</td>
                                <td>{{ $bahagian->nama }}</td>
                            </tr>
                        @endforeach
                    </table>
                </td>
            </tr>
        </table>
    </div>
</x-app-layout>

resources/views/user/update_password.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Users') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                <form method="POST" action="{{ route('users.update_password_submit') }}">
                    @csrf
                    @method('PUT')

                    <!-- Password -->
                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password"
                               name="password" :value="old('password')" required
                        >
                        @error('password')
                        <div class="text-red">{{ $message }}</div>
                        @enderror
                    </div>

                    <!-- Confirm Password -->
                    <div class="mb-3">
                        <label for="password_confirmation" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password_confirmation"
                               name="password_confirmation" :value="old('password_confirmation')" required
                        >
                        @error('password_confirmation')
                        <div class="text-red">{{ $message }}</div>
                        @enderror
                    </div>

                    <div class="pt-4">
                        <button class="btn btn-primary">
                            {{ __('Submit') }}
                        </button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>