routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   echo "HELLO. YOU ARE AT ADMIN SITE.";
});

routes/web.php
<?php

use App\Http\Controllers\AllUserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BahagianController;
use \Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::middleware('auth')
    ->group(function() {
    Route::get('users/update_password', [UserController::class, 'updatePasswordForm'])
        ->name('users.update_password');
    Route::put('users/update_password', [UserController::class, 'updatePasswordSubmit'])
        ->name('users.update_password_submit');

    Route::get('/publicusers/{id}', [UserController::class, 'exportToPdf']);

    Route::resource('/publicusers', UserController::class)->only(['index','show']);

    Route::prefix('admin')
        ->group(function() {
        Route::resource('/users', UserController::class);
        Route::resource('/bahagian', BahagianController::class);
    });
});

Route::get('/get-all-user', AllUserController::class);

//http://booking.test/test
Route::get('/test', function() {
    echo "HELLO, WORLD";
});

//http://booking.test/test/1/apa2
//http://booking.test/test/1
Route::get('/test/{a}/{name?}', function ($id, $name = null)
{
   echo "Hello, " . $id . $name ;
});

//http://booking.test/clash/kereta
Route::get('/clash/kereta', function() {
    echo "Masuk Situ Kereta" ;
});

//http://booking.test/clash/1
Route::get('/clash/{id}', function($id) {
    echo "Masuk Sini " . $id;
});

Route::get('/rawsql', function() {
    $users = DB::select("SELECT * FROM users WHERE id=? OR id=?", [1,400]);
    return $users;
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap"> -->

        <!-- Styles -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

        <link href="https://cdn.jsdelivr.net/npm/@coreui/coreui@4.0.2/dist/css/coreui.min.css" rel="stylesheet" integrity="sha384-qHZDARcDE4rvRsEXG23QUfqK+Pz9TDOdzRs1YuUyn4PfjMAJ9PbHcIZwg0Dx2yMP" crossorigin="anonymous">

        
    </head>
    <body>
        <div class="container-lg">
            @auth
                @include('layouts.navigation')
            @endauth
            <div class="container-lg">
            <!-- Page Heading -->
            <header class="header">
                    {{ $header }}
            </header>
        </div>

        <!-- Page Content -->
        <div class="container-lg">
            {{ $slot }}
        </div>

        @env('staging')
            <footer>
                THIS IS A STAGING SITE!!
            </footer>
        @endenv
        <script src="https://cdn.jsdelivr.net/npm/@coreui/coreui@4.0.2/dist/js/coreui.bundle.min.js" integrity="sha384-mUCFKFW9jQEIjhS6xOIxqiVI8jvvVKP9EU7P7Hu9CXqwso926ZGo41SQRhUX8CdC" crossorigin="anonymous"></script>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      CoreUI
    </a>
    <ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" href="{{ route('dashboard') }}">Dashboard</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ route('users.index') }}">Users</a>
  </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('bahagian.index') }}">Bahagians</a>
    </li>
  <li class="nav-item">
    <form method="POST" action="{{ route('logout') }}">
                            @csrf

        <a href="route('logout')" class="nav-link"
                onclick="event.preventDefault();
                            this.closest('form').submit();">
            {{ __('Log Out') }}
        </a>
    </form>
  </li>
</ul>
  </div>

</nav>